OrganicLifeWebMvc/Controllers/ClientesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OrganicLifeWebMvc.Data;
using OrganicLifeWebMvc.Models;
using OrganicLifeWebMvc.Services;

namespace OrganicLifeWebMvc.Controllers
{
    public class ClientesController : Controller
    {
        private readonly ClienteService _clienteService;
        private readonly UserService _userService;

        public ClientesController(ClienteService clienteService, UserService userService)
        {
            _clienteService = clienteService;
            _userService = userService;
        }

        // GET: Clientes
        public async Task<IActionResult> Index()
        {
            var user = await _userService.GetUserByName(User.Identity.Name);
            if (user == null || user.TipoUsuario.ToLower().Equals("fornecedor") || user.TipoUsuario.ToLower().Equals("cliente"))
                return RedirectToAction("Index", "Home");

            return View(await _clienteService.FindAllAsync());
        }

        // GET: Clientes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            var user = await _userService.GetUserByName(User.Identity.Name);
            if (user == null || user.TipoUsuario.ToLower().Equals("fornecedor") || user.TipoUsuario.ToLower().Equals("cliente"))
                return RedirectToAction("Index", "Home");

            if (id == null)
            {
                return NotFound();
            }

            var cliente = await _clienteService.FindByIdWithAssociationAsync((int)id);

            if (cliente == null)
            {
                return NotFound();
            }

            return View(cliente);
        }

        // GET: Clientes/Create
        public async Task<IActionResult> Create()
        {
            var user = await _userService.GetUserByName(User.Identity.Name);
            if (user == null || user.TipoUsuario.ToLower().Equals("fornecedor") || user.TipoUsuario.ToLower().Equals("cliente"))
                return RedirectToAction("Index", "Home");

            return View();
        }

        // POST: Clientes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Cliente cliente)
        {
            var user = await _userService.GetUserByName(User.Identity.Name);
            if (user == null || user.TipoUsuario.ToLower().Equals("fornecedor") || user.TipoUsuario.ToLower().Equals("cliente"))
                return RedirectToAction("Index", "Home");

            if (ModelState.IsValid)
            {
                await _clienteService.InsertAsync(cliente, user);
                return RedirectToAction(nameof(Index));
            }
            return View(cliente);
        }

        // GET: Clientes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            var user = await _userService.GetUserByName(User.Identity.Name);
            var idCliente = await _userService.IdClienteOrFornecedorByUser(user.UserName);
            if(idCliente > 0 && idCliente == id)
            {
                var clienteLogado = await _clienteService.FindByIdWithAssociationAsync((int)id);
                if (clienteLogado == null)
                {
                    return NotFound();
                }
                return View(clienteLogado);
            }

            if (user == null || user.TipoUsuario.ToLower().Equals("fornecedor") || user.TipoUsuario.ToLower().Equals("cliente"))
                return RedirectToAction("Index", "Home");

            if (id == null)
            {
                return NotFound();
            }

            var cliente = await _clienteService.FindByIdWithAssociationAsync((int)id);
            if (cliente == null)
            {
                return NotFound();
            }
            return View(cliente);
        }

        // POST: Clientes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,DataHoraCadastro,ResponsavelCadastro,DataHoraAlteracao,ResponsavelAlteracao,Pessoa")] Cliente cliente)
        {
            var user = await _userService.GetUserByName(User.Identity.Name);
            var idCliente = await _userService.IdClienteOrFornecedorByUser(user.UserName);

            if(idCliente != id)
                if (user == null || user.TipoUsuario.ToLower().Equals("fornecedor") || user.TipoUsuario.ToLower().Equals("cliente"))
                    return RedirectToAction("Index", "Home");

            if (id != cliente.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _clienteService.UpdateAsync(cliente, user);
                }
                catch (DbUpdateConcurrencyException)
                {
                    var clienteExist = await _clienteService.ClienteExistAsync(cliente.Id);
                    if (!clienteExist)
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(cliente);
        }

        // GET: Clientes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            var user = await _userService.GetUserByName(User.Identity.Name);
            if (user == null || user.TipoUsuario.ToLower().Equals("fornecedor") || user.TipoUsuario.ToLower().Equals("cliente"))
                return RedirectToAction("Index", "Home");

            if (id == null)
            {
                return NotFound();
            }

            var cliente = await _clienteService.FindByIdAsync((int)id);

            if (cliente == null)
            {
                return NotFound();
            }

            return View(cliente);
        }

        // POST: Clientes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var user = await _userService.GetUserByName(User.Identity.Name);
            if (user == null || user.TipoUsuario.ToLower().Equals("fornecedor") || user.TipoUsuario.ToLower().Equals("cliente"))
                return RedirectToAction("Index", "Home");

            var cliente = await _clienteService.FindByIdAsync((int)id);
            await _clienteService.DeleteAsync(cliente);
            return RedirectToAction(nameof(Index));
        }
    }
}

OrganicLifeWebMvc/Controllers/ProdutosController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OrganicLifeWebMvc.Controllers;
using OrganicLifeWebMvc.Models;
using OrganicLifeWebMvc.Services;

namespace OrganicLifeWebMvc.Views
{
    public class ProdutosController : Controller
    {
        private readonly ProdutoService _produtoService;
        private readonly UserService _userService;
        private readonly FornecedorService _fornecedorService;

        public ProdutosController(ProdutoService context, UserService userService, FornecedorService fornecedorService)
        {
            _produtoService = context;
            _userService = userService;
            _fornecedorService = fornecedorService;
        }

        private async Task<bool> ValidarUsuario()
        {
            var user = await _userService.GetUserByName(User.Identity.Name);
            if(user == null)
                return false;

            if (user.TipoUsuario.ToLower().Equals("admin") || user.TipoUsuario.ToLower().Equals("fornecedor"))
                return true;

            return false;
        }

        // GET: Produtos
        public async Task<IActionResult> Index()
        {
            var user = await _userService.GetUserByName(User.Identity.Name);
            if(user == null || user.TipoUsuario.ToLower().Equals("cliente"))
                return RedirectToAction("Index", "Home");
            if (user.TipoUsuario.ToLower().Equals("admin"))
                return View(await _produtoService.FindAllWithAssociationAsync());
            else
            {
                var fornecedor = _fornecedorService.GetFornecedorByUser(user);
                return View(await _produtoService.FindAllWithAssociationByFornecedor(fornecedor.Id));
            }
        }

        // GET: Produtos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            var user = await _userService.GetUserByName(User.Identity.Name);
            if (user == null || user.TipoUsuario.ToLower().Equals("cliente"))
                return RedirectToAction("Index", "Home");

            if (id == null)
            {
                return NotFound();
            }

            var produto = await _produtoService.FindByIdWithAssociationAsync((int)id);
            if (produto == null)
            {
                return NotFound();
            }

            return View(produto);
        }

        // GET: Produtos/Create
        public async Task<IActionResult> Create()
        {
            var user = await _userService.GetUserByName(User.Identity.Name);
            if (user == null || user.TipoUsuario.ToLower().Equals("cliente"))
                return RedirectToAction("Index", "Home");

            return View();
        }

        // POST: Produtos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Sigla,Nome,Descricao,Valor,Categoria,Organico,Deletado,DataHoraExclusao,ResponsavelExclusao,Id,DataHoraCadastro,ResponsavelCadastro,DataHoraAlteracao,ResponsavelAlteracao")] Produto produto)
        {
            var user = await _userService.GetUserByName(User.Identity.Name);
            if (user == null || user.TipoUsuario.ToLower().Equals("cliente"))
                return RedirectToAction("Index", "Home");

            if (ModelState.IsValid)
            {
                await _produtoService.InsertAsync(produto, user);
                return RedirectToAction(nameof(Index));
            }
            return View(produto);
        }

        // GET: Produtos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            var user = await _userService.GetUserByName(User.Identity.Name);
            if (user == null || user.TipoUsuario.ToLower().Equals("cliente"))
                return RedirectToAction("Index", "Home");

            if (id == null)
            {
                return NotFound();
            }

            var produto = await _produtoService.FindByIdWithAssociationAsync((int)id);

            if (produto == null)
            {
                return NotFound();
            }
            return View(produto);
        }

        // POST: Produtos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Sigla,Nome,Descricao,Valor,Categoria,Organico,Deletado,DataHoraExclusao,ResponsavelExclusao,Id,DataHoraCadastro,ResponsavelCadastro,DataHoraAlteracao,ResponsavelAlteracao")] Produto produto)
        {
            var user = await _userService.GetUserByName(User.Identity.Name);
            if (user == null || user.TipoUsuario.ToLower().Equals("cliente"))
                return RedirectToAction("Index", "Home");

            if (id != produto.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _produtoService.UpdateAsync(produto, user);
                }
                catch (DbUpdateConcurrencyException)
                {
                    var produtoExist = await _produtoService.ProdutoExistAsync(produto.Id);
                    if (!produtoExist)
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(produto);
        }

        // GET: Produtos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            var user = await _userService.GetUserByName(User.Identity.Name);
            if (user == null || user.TipoUsuario.ToLower().Equals("cliente"))
                return RedirectToAction("Index", "Home");

            if (id == null)
            {
                return NotFound();
            }

            var produto = await _produtoService.FindByIdWithAssociationAsync((int)id);

            if (produto == null)
            {
                return NotFound();
            }

            return View(produto);
        }

        // POST: Produtos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var user = await _userService.GetUserByName(User.Identity.Name);
            if (user == null || user.TipoUsuario.ToLower().Equals("cliente"))
                return RedirectToAction("Index", "Home");

            var produto = await _produtoService.FindByIdWithAssociationAsync(id);
            await _produtoService.DeleteSoftAsync(produto, user);
            return RedirectToAction(nameof(Index));
        }
    }
}

OrganicLifeWebMvc/Controllers/RelatoriosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OrganicLifeWebMvc.Data;
using OrganicLifeWebMvc.Models;
using OrganicLifeWebMvc.Services;

namespace OrganicLifeWebMvc.Controllers
{
    public class RelatoriosController : Controller
    {
        private readonly VendaService _vendaService;
        private readonly UserService _userService;
        private readonly FornecedorService _fornecedorService;
        private readonly ClienteService _clienteService;

        public RelatoriosController(VendaService vendaService, UserService userService, FornecedorService fornecedorService, ClienteService clienteService)
        {
            _vendaService = vendaService;
            _userService = userService;
            _fornecedorService = fornecedorService;
            _clienteService = clienteService;
        }

        // GET: RelatoriosVendas
        public async Task<IActionResult> RelatorioVendas()
        {
            var user = await _userService.GetUserByName(User.Identity.Name);
            if (user == null || user.TipoUsuario.ToLower().Equals("cliente"))
                return RedirectToAction("Index", "Home");

            var fornecedor = _fornecedorService.GetFornecedorByUser(user);

            return View(await _vendaService.FindAllWithAssociationByFornecedorAsync(fornecedor.Id));
        }

        // GET: RelatoriosCompras
        public async Task<IActionResult> RelatorioCompras()
        {
            var user = await _userService.GetUserByName(User.Identity.Name);
            if (user == null || user.TipoUsuario.ToLower().Equals("fornecedor"))
                return RedirectToAction("Index", "Home");

            var cliente = _clienteService.GetClienteByUser(user);

            return View(await _vendaService.FindAllWithAssociationByClienteAsync(cliente.Id));
        }
    }
}

OrganicLifeWebMvc/Controllers/VendasController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OrganicLifeWebMvc.Models;
using OrganicLifeWebMvc.Services;

namespace OrganicLifeWebMvc.Controllers
{
    public class VendasController : Controller
    {
        private readonly VendaService _vendaService;
        private readonly FornecedorService _fornecedorService;
        private readonly ProdutoService _produtoService;
        private readonly UserService _userService;

        public VendasController(
            VendaService vendaService, 
            FornecedorService fornecedorService, 
            ProdutoService produtoService, 
            UserService userService)
        {
            _vendaService = vendaService;
            _fornecedorService = fornecedorService;
            _produtoService = produtoService;
            _userService = userService;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _fornecedorService.FindAllWithAssociationAsync());
        }
        public async Task<IActionResult> Carrinho()
        {
            return View(await _vendaService.FindAllWithAssociationAsync());
        }

        public async Task<IActionResult> ProdutosLista(int? id)
        {
            if (id == null || id <= 0)
            {
                return NotFound();
            }

            return View(await _produtoService.FindAllWithAssociationByFornecedor((int)id));
        }
    }
}

OrganicLifeWebMvc/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using OrganicLifeWebMvc.Services

@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
@inject UserService UserService

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Organic Life</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-flatly.css" />
        <link rel="stylesheet" href="~/css/StyleSheet.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container" style="width:95%;">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index"><img src="~/images/Logo_Organic_Life.png" style="height:50px; margin-top:5px; margin-right:30px;"></a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Início</a></li>
                    @if (SignInManager.IsSignedIn(User) && await UserService.UserIsAdmin(User.Identity.Name))
                    {
                        <li><a asp-area="" asp-controller="Clientes" asp-action="Index">Clientes</a></li>
                    }
                    @if (SignInManager.IsSignedIn(User) && await UserService.UserIsAdmin(User.Identity.Name))
                    {
                        <li><a asp-area="" asp-controller="Fornecedores" asp-action="Index">Fornecedores</a></li>
                    }
                    @if (SignInManager.IsSignedIn(User) && (await UserService.UserIsAdmin(User.Identity.Name) || await UserService.UserIsFornecedor(User.Identity.Name)))
                    {
                        <li><a asp-area="" asp-controller="Produtos" asp-action="Index">Produtos</a></li>
                    }
                    @if (SignInManager.IsSignedIn(User) && (await UserService.UserIsAdmin(User.Identity.Name) || await UserService.UserIsFornecedor(User.Identity.Name)))
                    {
                        <li><a asp-area="" asp-controller="Relatorios" asp-action="RelatorioVendas">Minhas Vendas</a></li>
                    }
                    @if (SignInManager.IsSignedIn(User) && (await UserService.UserIsAdmin(User.Identity.Name) || await UserService.UserIsCliente(User.Identity.Name)))
                    {
                        <li><a asp-area="" asp-controller="Relatorios" asp-action="RelatorioCompras">Minhas Compras</a></li>
                    }
                    <li><a asp-area="" asp-controller="Vendas" asp-action="Index">Produtores</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">Sobre</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contato</a></li>
                </ul>              
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p style="text-align:center;">&copy; 2021 - Organic Life - Todos os direitos reservados.</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>